### ISSUE TITLE
[Feature Request] Use schema file 

### ISSUE THREAD

**Issue by dreulavelle** [semanser/JsonGenius#1]
To keep clutter down and editing the schema, or trying different schema's even easier, would be nice to be able to use a file instead of passing the schema through as an argument.

If it isn't possible, thats alright. 

Interesting work so far, can't wait to see use cases for this outside of scraping amazon ;)

**Comment by semanser** [comment]
I think this is an interesting idea and it shouldn't be hard to implement. 👍

**Comment by dreulavelle** [comment]
Thank you! :)
