### ISSUE TITLE
best way to use the response data outside of docker?

### ISSUE THREAD

**Issue by strid3r21** [semanser/JsonGenius#4]
whats the best way to pole the response data and use it outside of docker?

im writing a basic javascript front end webpage to enter a url that then gets posted to JsonGenius with the url and schema. this works. however i cant seem to get the response data back. id like to be able to use that response data in the webpage.

the javascript function is pretty simple using the fetch API.

```
const sendURLtoJsonGenius = async () => {
try{
	const response = await fetch('http://localhost:3001/lookup', {
	method: 'POST',
	mode: 'no-cors',
	headers: { "Content-Type": "application/json" },
	body: jsonPackage ,
});
	
	  const data = await response.json()
	  console.log("Success:",data)
	  
	}catch(error) {
		console.log("error:", error)
	}
}
```

the await response.json() is where this fails as far as i can tell. 

any advice or ideas on how i can get this working?

**Comment by semanser** [comment]
Hi,

There are no pre-built executables for jsongenius (yet), but you could try to compile it on your own if you would like. It should be as simple as running go build . (assuming that you have the Go language toolchain installed).

Also, you should be able to "poll the response data and use it outside of Docker" right now. In your example above, you're making a request to the Docker container, and you should be able to get the response back. Can you provide your console.log("error:", error) output?

**Comment by strid3r21** [comment]
so i laterally just figured it out. it was a CORs issue that was blocking the return response.

since im testing this locally my web page is at localhost:3000 and jsonGenius is on 3001
 
i just needed to start a CORs proxy and use that as an in-between.

so for others that may run into this, this is what i did.


#1 in new terminal install this CORs proxy server 

`npm install -g local-cors-proxy`

then start the proxy server for JsonGenius like so

`lcp --proxyUrl http://localhost:3001`

this will start the proxy server. leave it running while you work.

then in javascript code use that proxy like so.

```
const jsonPackage = JSON.stringify({
  "url": "https://www.amazon.com/s?k=gaming+headsets",
  "schema": {
    "type": "object",
    "properties": {
      "products": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "The product name"
            },
            "price": {
              "type": "number",
              "description": "The price of the product in USD"
            }
          }
        }
      }
    }
  }
})

const sendURLtoJsonGenius = async () => {
try{
	const response = await fetch('http://localhost:8010/proxy/lookup', {  <---------------
	method: 'POST',
	mode: 'cors',
	headers: { "Content-Type": "application/json" },
	body: jsonPackage ,
});	
	  const data = await response.json() <---the results come in here
	  console.log("Success:",data)
}catch(error) {
	console.log("error:", error)
}
}
```

which returns the results in the webpage like so 
![jsonGenius-web](https://github.com/semanser/JsonGenius/assets/56952812/80410cba-7ebc-4249-8c6d-e9342d8ca092)

**Comment by semanser** [comment]
Nice, glad to see you solved it!
